### ISSUE TITLE
BufferError: Existing exports of data: object cannot be re-sized

### ISSUE THREAD

**Issue by lnbob** [quantaosun/pl3#1]
When I configured the environment to run the test using the original data, prompt the error

BufferError: Existing exports of data: object cannot be re-sized
Exception in callback BaseAsyncIOLoop._handle_events(32, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(32, 1)>
Traceback (most recent call last):
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
    return callback(self, msg)
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
    super()._on_zmq_reply(stream, msg)
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
    self.write_message(msg, binary=isinstance(msg, bytes))
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/tornado/websocket.py", line 339, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/tornado/websocket.py", line 1086, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/tornado/websocket.py", line 1061, in _write_frame
    return self.stream.write(frame)
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/tornado/iostream.py", line 540, in write
    self._write_buffer.append(data)
  File "/home/lbsky/miniconda3/envs/webdock/lib/python3.8/site-packages/tornado/iostream.py", line 157, in append
    b += data  # type: ignore
BufferError: Existing exports of data: object cannot be re-sized

**Comment by lnbob** [comment]
It's really interesting. To solve this problem, I ran the code one by one, but it didn't get this error, it ran smoothly, amazing

**Comment by quantaosun** [comment]
This repo was originally designed to use online with Binder so the environment.yml file can be further improved for local use.

 If you click the binder button in README and wait for a short time it will load a browser window for docking with environment all set. Just download the docked result in time before Binder session goes idle.

For a better exprience you are suggested to use another repository named labodock_binder, also in a online manner.
